/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as CoreRouteImport } from './routes/_core'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicLearnRouteImport } from './routes/_public/learn'
import { Route as CoreSettingsRouteImport } from './routes/_core/settings'
import { Route as CorePricingAdminRouteImport } from './routes/_core/pricing-admin'
import { Route as CoreDashboardRouteImport } from './routes/_core/dashboard'
import { Route as TenantProductsIndexRouteImport } from './routes/_tenant/products/index'
import { Route as CoreSettingsIndexRouteImport } from './routes/_core/settings/index'
import { Route as TenantProductsIdRouteImport } from './routes/_tenant/products/$id'
import { Route as PublicLearnTermsRouteImport } from './routes/_public/learn/terms'
import { Route as PublicLearnPrivacyRouteImport } from './routes/_public/learn/privacy'
import { Route as PublicLearnCookiesRouteImport } from './routes/_public/learn/cookies'
import { Route as CoreSettingsRolesRouteImport } from './routes/_core/settings/roles'
import { Route as CoreSettingsProfileRouteImport } from './routes/_core/settings/profile'
import { Route as CoreSettingsPersonalRouteImport } from './routes/_core/settings/personal'
import { Route as CoreSettingsPasswordRouteImport } from './routes/_core/settings/password'
import { Route as CoreSettingsContactsRouteImport } from './routes/_core/settings/contacts'
import { Route as CoreSettingsAppearanceRouteImport } from './routes/_core/settings/appearance'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/_core',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLearnRoute = PublicLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => PublicRoute,
} as any)
const CoreSettingsRoute = CoreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoreRoute,
} as any)
const CorePricingAdminRoute = CorePricingAdminRouteImport.update({
  id: '/pricing-admin',
  path: '/pricing-admin',
  getParentRoute: () => CoreRoute,
} as any)
const CoreDashboardRoute = CoreDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CoreRoute,
} as any)
const TenantProductsIndexRoute = TenantProductsIndexRouteImport.update({
  id: '/_tenant/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreSettingsIndexRoute = CoreSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoreSettingsRoute,
} as any)
const TenantProductsIdRoute = TenantProductsIdRouteImport.update({
  id: '/_tenant/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLearnTermsRoute = PublicLearnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicLearnRoute,
} as any)
const PublicLearnPrivacyRoute = PublicLearnPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicLearnRoute,
} as any)
const PublicLearnCookiesRoute = PublicLearnCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicLearnRoute,
} as any)
const CoreSettingsRolesRoute = CoreSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => CoreSettingsRoute,
} as any)
const CoreSettingsProfileRoute = CoreSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CoreSettingsRoute,
} as any)
const CoreSettingsPersonalRoute = CoreSettingsPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => CoreSettingsRoute,
} as any)
const CoreSettingsPasswordRoute = CoreSettingsPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => CoreSettingsRoute,
} as any)
const CoreSettingsContactsRoute = CoreSettingsContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CoreSettingsRoute,
} as any)
const CoreSettingsAppearanceRoute = CoreSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => CoreSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof CoreDashboardRoute
  '/pricing-admin': typeof CorePricingAdminRoute
  '/settings': typeof CoreSettingsRouteWithChildren
  '/learn': typeof PublicLearnRouteWithChildren
  '/pricing': typeof PublicPricingRoute
  '/': typeof PublicIndexRoute
  '/settings/appearance': typeof CoreSettingsAppearanceRoute
  '/settings/contacts': typeof CoreSettingsContactsRoute
  '/settings/password': typeof CoreSettingsPasswordRoute
  '/settings/personal': typeof CoreSettingsPersonalRoute
  '/settings/profile': typeof CoreSettingsProfileRoute
  '/settings/roles': typeof CoreSettingsRolesRoute
  '/learn/cookies': typeof PublicLearnCookiesRoute
  '/learn/privacy': typeof PublicLearnPrivacyRoute
  '/learn/terms': typeof PublicLearnTermsRoute
  '/products/$id': typeof TenantProductsIdRoute
  '/settings/': typeof CoreSettingsIndexRoute
  '/products': typeof TenantProductsIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof CoreDashboardRoute
  '/pricing-admin': typeof CorePricingAdminRoute
  '/learn': typeof PublicLearnRouteWithChildren
  '/pricing': typeof PublicPricingRoute
  '/': typeof PublicIndexRoute
  '/settings/appearance': typeof CoreSettingsAppearanceRoute
  '/settings/contacts': typeof CoreSettingsContactsRoute
  '/settings/password': typeof CoreSettingsPasswordRoute
  '/settings/personal': typeof CoreSettingsPersonalRoute
  '/settings/profile': typeof CoreSettingsProfileRoute
  '/settings/roles': typeof CoreSettingsRolesRoute
  '/learn/cookies': typeof PublicLearnCookiesRoute
  '/learn/privacy': typeof PublicLearnPrivacyRoute
  '/learn/terms': typeof PublicLearnTermsRoute
  '/products/$id': typeof TenantProductsIdRoute
  '/settings': typeof CoreSettingsIndexRoute
  '/products': typeof TenantProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_core': typeof CoreRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_core/dashboard': typeof CoreDashboardRoute
  '/_core/pricing-admin': typeof CorePricingAdminRoute
  '/_core/settings': typeof CoreSettingsRouteWithChildren
  '/_public/learn': typeof PublicLearnRouteWithChildren
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/': typeof PublicIndexRoute
  '/_core/settings/appearance': typeof CoreSettingsAppearanceRoute
  '/_core/settings/contacts': typeof CoreSettingsContactsRoute
  '/_core/settings/password': typeof CoreSettingsPasswordRoute
  '/_core/settings/personal': typeof CoreSettingsPersonalRoute
  '/_core/settings/profile': typeof CoreSettingsProfileRoute
  '/_core/settings/roles': typeof CoreSettingsRolesRoute
  '/_public/learn/cookies': typeof PublicLearnCookiesRoute
  '/_public/learn/privacy': typeof PublicLearnPrivacyRoute
  '/_public/learn/terms': typeof PublicLearnTermsRoute
  '/_tenant/products/$id': typeof TenantProductsIdRoute
  '/_core/settings/': typeof CoreSettingsIndexRoute
  '/_tenant/products/': typeof TenantProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/pricing-admin'
    | '/settings'
    | '/learn'
    | '/pricing'
    | '/'
    | '/settings/appearance'
    | '/settings/contacts'
    | '/settings/password'
    | '/settings/personal'
    | '/settings/profile'
    | '/settings/roles'
    | '/learn/cookies'
    | '/learn/privacy'
    | '/learn/terms'
    | '/products/$id'
    | '/settings/'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/pricing-admin'
    | '/learn'
    | '/pricing'
    | '/'
    | '/settings/appearance'
    | '/settings/contacts'
    | '/settings/password'
    | '/settings/personal'
    | '/settings/profile'
    | '/settings/roles'
    | '/learn/cookies'
    | '/learn/privacy'
    | '/learn/terms'
    | '/products/$id'
    | '/settings'
    | '/products'
  id:
    | '__root__'
    | '/_core'
    | '/_public'
    | '/_core/dashboard'
    | '/_core/pricing-admin'
    | '/_core/settings'
    | '/_public/learn'
    | '/_public/pricing'
    | '/_public/'
    | '/_core/settings/appearance'
    | '/_core/settings/contacts'
    | '/_core/settings/password'
    | '/_core/settings/personal'
    | '/_core/settings/profile'
    | '/_core/settings/roles'
    | '/_public/learn/cookies'
    | '/_public/learn/privacy'
    | '/_public/learn/terms'
    | '/_tenant/products/$id'
    | '/_core/settings/'
    | '/_tenant/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CoreRoute: typeof CoreRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  TenantProductsIdRoute: typeof TenantProductsIdRoute
  TenantProductsIndexRoute: typeof TenantProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_core': {
      id: '/_core'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/learn': {
      id: '/_public/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof PublicLearnRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_core/settings': {
      id: '/_core/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CoreSettingsRouteImport
      parentRoute: typeof CoreRoute
    }
    '/_core/pricing-admin': {
      id: '/_core/pricing-admin'
      path: '/pricing-admin'
      fullPath: '/pricing-admin'
      preLoaderRoute: typeof CorePricingAdminRouteImport
      parentRoute: typeof CoreRoute
    }
    '/_core/dashboard': {
      id: '/_core/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof CoreDashboardRouteImport
      parentRoute: typeof CoreRoute
    }
    '/_tenant/products/': {
      id: '/_tenant/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof TenantProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_core/settings/': {
      id: '/_core/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof CoreSettingsIndexRouteImport
      parentRoute: typeof CoreSettingsRoute
    }
    '/_tenant/products/$id': {
      id: '/_tenant/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof TenantProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/learn/terms': {
      id: '/_public/learn/terms'
      path: '/terms'
      fullPath: '/learn/terms'
      preLoaderRoute: typeof PublicLearnTermsRouteImport
      parentRoute: typeof PublicLearnRoute
    }
    '/_public/learn/privacy': {
      id: '/_public/learn/privacy'
      path: '/privacy'
      fullPath: '/learn/privacy'
      preLoaderRoute: typeof PublicLearnPrivacyRouteImport
      parentRoute: typeof PublicLearnRoute
    }
    '/_public/learn/cookies': {
      id: '/_public/learn/cookies'
      path: '/cookies'
      fullPath: '/learn/cookies'
      preLoaderRoute: typeof PublicLearnCookiesRouteImport
      parentRoute: typeof PublicLearnRoute
    }
    '/_core/settings/roles': {
      id: '/_core/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof CoreSettingsRolesRouteImport
      parentRoute: typeof CoreSettingsRoute
    }
    '/_core/settings/profile': {
      id: '/_core/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof CoreSettingsProfileRouteImport
      parentRoute: typeof CoreSettingsRoute
    }
    '/_core/settings/personal': {
      id: '/_core/settings/personal'
      path: '/personal'
      fullPath: '/settings/personal'
      preLoaderRoute: typeof CoreSettingsPersonalRouteImport
      parentRoute: typeof CoreSettingsRoute
    }
    '/_core/settings/password': {
      id: '/_core/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof CoreSettingsPasswordRouteImport
      parentRoute: typeof CoreSettingsRoute
    }
    '/_core/settings/contacts': {
      id: '/_core/settings/contacts'
      path: '/contacts'
      fullPath: '/settings/contacts'
      preLoaderRoute: typeof CoreSettingsContactsRouteImport
      parentRoute: typeof CoreSettingsRoute
    }
    '/_core/settings/appearance': {
      id: '/_core/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof CoreSettingsAppearanceRouteImport
      parentRoute: typeof CoreSettingsRoute
    }
  }
}

interface CoreSettingsRouteChildren {
  CoreSettingsAppearanceRoute: typeof CoreSettingsAppearanceRoute
  CoreSettingsContactsRoute: typeof CoreSettingsContactsRoute
  CoreSettingsPasswordRoute: typeof CoreSettingsPasswordRoute
  CoreSettingsPersonalRoute: typeof CoreSettingsPersonalRoute
  CoreSettingsProfileRoute: typeof CoreSettingsProfileRoute
  CoreSettingsRolesRoute: typeof CoreSettingsRolesRoute
  CoreSettingsIndexRoute: typeof CoreSettingsIndexRoute
}

const CoreSettingsRouteChildren: CoreSettingsRouteChildren = {
  CoreSettingsAppearanceRoute: CoreSettingsAppearanceRoute,
  CoreSettingsContactsRoute: CoreSettingsContactsRoute,
  CoreSettingsPasswordRoute: CoreSettingsPasswordRoute,
  CoreSettingsPersonalRoute: CoreSettingsPersonalRoute,
  CoreSettingsProfileRoute: CoreSettingsProfileRoute,
  CoreSettingsRolesRoute: CoreSettingsRolesRoute,
  CoreSettingsIndexRoute: CoreSettingsIndexRoute,
}

const CoreSettingsRouteWithChildren = CoreSettingsRoute._addFileChildren(
  CoreSettingsRouteChildren,
)

interface CoreRouteChildren {
  CoreDashboardRoute: typeof CoreDashboardRoute
  CorePricingAdminRoute: typeof CorePricingAdminRoute
  CoreSettingsRoute: typeof CoreSettingsRouteWithChildren
}

const CoreRouteChildren: CoreRouteChildren = {
  CoreDashboardRoute: CoreDashboardRoute,
  CorePricingAdminRoute: CorePricingAdminRoute,
  CoreSettingsRoute: CoreSettingsRouteWithChildren,
}

const CoreRouteWithChildren = CoreRoute._addFileChildren(CoreRouteChildren)

interface PublicLearnRouteChildren {
  PublicLearnCookiesRoute: typeof PublicLearnCookiesRoute
  PublicLearnPrivacyRoute: typeof PublicLearnPrivacyRoute
  PublicLearnTermsRoute: typeof PublicLearnTermsRoute
}

const PublicLearnRouteChildren: PublicLearnRouteChildren = {
  PublicLearnCookiesRoute: PublicLearnCookiesRoute,
  PublicLearnPrivacyRoute: PublicLearnPrivacyRoute,
  PublicLearnTermsRoute: PublicLearnTermsRoute,
}

const PublicLearnRouteWithChildren = PublicLearnRoute._addFileChildren(
  PublicLearnRouteChildren,
)

interface PublicRouteChildren {
  PublicLearnRoute: typeof PublicLearnRouteWithChildren
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLearnRoute: PublicLearnRouteWithChildren,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CoreRoute: CoreRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  TenantProductsIdRoute: TenantProductsIdRoute,
  TenantProductsIndexRoute: TenantProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
